<div class="find-owner-form">
  <form class="" action="addProperty.php" method="post">
    <div class="form-group row">
      <div class="col-md-6">
        <label for="ownerID" class="form-label mt-2">Owner ID: </label>
        <input type="text" class="form-control form-control-sm" name="ownerID" value="">
      </div>
    </div>
    <div class="form-buttons">
      <input class="btn btn-primary" type="submit" name="newProp" value="Start New Property"><input class="btn btn-primary" type="submit" name="findOwner" value="Find Owners">
    </div>
  </form>
</div>
